name: MyPet
main: de.Keyle.MyPet.MyPetPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: Keyle
website: ${project.url}
softdepend: [Vault, Heroes, Ancient, BattleArena, Minigames, MobArena, pvparena, Multiverse-Core, SurvivalGames, ProtocolLib, SkillAPI, MagicSpells]
commands:
  myPet:
    description: Help for all MyPet commands.
  petname:
    description: Changes the name of your MyPet
    usage: '/<command> <PetName>'
    permission: MyPet.command.name
  petcall:
    aliases: [petc, pc]
    description: Calls your MyPet.
  petsendaway:
    aliases: [petsa, psa]
    description: Send your MyPet away.
  petrelease:
    description: Releases your MyPet.
    usage: '/<command> <PetName>'
    permission: MyPet.command.release
  petstop:
    aliases: [pets, ps]
    description: Stops your MyPet from attacking.
  petpickup:
    aliases: [petp, pp]
    description: Toogles pickup of your MyPet.
  petinventory:
    aliases: [peti, pi]
    description: Opens the inventory of your MyPet.
  petbehavior:
    aliases: [petb, pb]
    description: Changes the behavior mode of your MyPet.
    usage: '/<command> [<friendly/friend/aggressive/aggro/normal/farm/raid/duel>]'
  petinfo:
    aliases: [pinfo]
    description: Shows info about your MyPet
    usage: '/<command> [PlayerName]'
  petskill:
    aliases: [pskill]
    description: Shows the Skill-levels of your MyPet
    usage: '/<command> <Playername>'
  mypetadmin:
    aliases: [petadmin]
    description: ยง6MyPet-Admin-Command ยงr-> ยง3https://wiki.mypet-plugin.de/doku.php?id=en:commands
    permission: MyPet.admin
  petskilltree:
    aliases: [pst, petst]
    description: Shows a fully configured skilltree
    usage: '/<command> <mobtype> [SkillTreeName]'
  petchooseskilltree:
    aliases: [pcst, petcst]
    description: Chooses a skilltree.
    usage: '/<command> <SkillTreeName>'
  petbeacon:
    aliases: [pbeacon]
    description: Beacon!
  petrespawn:
    aliases: [pr, petr]
    description: Pays respawn fee or enable auto respawn fee paying.
    usage: '/<command> [pay/auto] [min respawn time]'
    permission: MyPet.command.respawn
  pettype:
    description: Shows info about the MyPet-types.
    usage: '/<command> <Pettype>'
  petcapturehelper:
    aliases: [pch]
    description: Toogles CaptureHelper on/off
    usage: '/<command>'
    permission: MyPet.command.capturehelper
  petoptions:
    aliases: [po, peto, petoption]
    description: MyPet player options
    usage: '/<command>'
    permission: MyPet.command.options
  petswitch:
    aliases: [pswitch, psw]
    description: Opens a MyPet selection GUI
    usage: '/<command>'
    permission: MyPet.command.switch
  petlist:
    aliases: [plist, pl]
    description: Lists all your MyPets
    usage: '/<command> <player>'
    permission: MyPet.command.list

permissions:
  MyPet.leash.*:
    description: Player can leash all MyPet-Types.
    children:
      MyPet.leash.Bat: true
      MyPet.leash.Blaze: true
      MyPet.leash.CaveSpider: true
      MyPet.leash.Chicken: true
      MyPet.leash.Cow: true
      MyPet.leash.Creeper: true
      MyPet.leash.Enderdragon: true
      MyPet.leash.Enderman: true
      MyPet.leash.Endermite: true
      MyPet.leash.Giant: true
      MyPet.leash.Ghast: true
      MyPet.leash.Guardian: true
      MyPet.leash.Horse: true
      MyPet.leash.IronGolem: true
      MyPet.leash.MagmaCube: true
      MyPet.leash.Mooshroom: true
      MyPet.leash.Ocelot: true
      MyPet.leash.Pig: true
      MyPet.leash.PigZombie: true
      MyPet.leash.Rabbit: true
      MyPet.leash.Sheep: true
      MyPet.leash.Silverfish: true
      MyPet.leash.Skeleton: true
      MyPet.leash.Slime: true
      MyPet.leash.Snowman: true
      MyPet.leash.Spider: true
      MyPet.leash.Squid: true
      MyPet.leash.Villager: true
      MyPet.leash.Witch: true
      MyPet.leash.Wither: true
      MyPet.leash.Wolf: true
      MyPet.leash.Zombie: true
  MyPet.admin:
    description: Gives access to the MyPet admin features.
    default: op
  MyPet.*:
    description: Gives access to MyPet features for normal user.
    children:
      MyPet.leash.*: true
      MyPet.command.respawn: true
      MyPet.command.release: true
      MyPet.command.capturehelper: true
      MyPet.command.name: true
      MyPet.command.name.color: true
      MyPet.command.options: true
      MyPet.command.list: true
  MyPet.command.release:
    default: true
    description: Allows usage of /petrelease
  MyPet.command.capturehelper:
    default: true
    description: Gives access to the CaptureHelper
  MyPet.command.respawn:
    default: true
    description: Allows usage of /petrespawn
  MyPet.command.name:
    default: true
    description: Allows usage of /petname
  MyPet.command.name.color:
    default: true
    description: Allows to use colors in petnames
  MyPet.command.options:
    default: true
    description: Allows to use the MyPet options command
  MyPet.command.switch:
    default: op
    description: Allows to switch between MyPets
  MyPet.command.info.other:
    default: op
    description: Allows to view info about pets from other players with "/petinfo <playername>"